---
title: "Study Notes in Statistics and Data AnalysisYo"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
  ioslides_presentation:
    toc: true
  word_document:
    toc: true
  beamer_presentation:
    toc: true
    latex_engine: xelatex
  pdf_document:
    toc: true
    latex_engine: xelatex
header-includes:
  - \usepackage{xeCJK}
  - \setCJKmainfont{Hiragino Mincho Pro}
---

#### Fundamentals of Statistics
- Hypothesis Testing and P-values
- Confidence Intervals
- Errors and Power
- Measures of Central Tendency
- Measures of Variability
- Measures of Shape
- Graphical Summaries

#### Data Collection and Design of Experiments
- Sampling Methods
- Bias and Error
- Principles of Experimental Design
- Design of Surveys and Questionnaires

#### Understanding Distributions and Tests
- Normal Distribution and Central Limit Theorem
- Introdcuction to Z-Tests and Non-parametric Tests

#### T-Tests and Related Non-parametric Tests
- One-sample T-Test and Non-parametric Equivalent (Wilcoxon Signed-Rank Test)
- Independent-samples T-Test and Non-parametric Equivalent (Mann-Whitney U test)
- Paired-samples T-Test and Non-parametric Equivalent (Wilcoxon Signed-Rank Test)
   
#### Chi-Square Tests
- Chi-square Goodness of Fit
- Chi-square Test for Independence
- Chi-square Test for Homogeneity

#### Analysis Using F-Statistic
- Analysis of Variance (ANOVA) and Non-parametric Equivalent (Kruskal-Wallis Test)
- Factorial and Repeated Measures ANOVA
- Analysis of Covariance (ANCOVA)
- Multivariate Analysis of Variance (MANOVA) and Covariance (MANCOVA)

#### Regression and Correlation Analysis
- Simple and Multiple Linear Regression
- Polynomial and Ridge Regression
- Logistic Regression
- Correlation Analysis (Pearson's, Spearman's, Point-biserial)

#### Generalized Models
- Generalized Linear Models (GLM)
- Generalized Linear Mixed Models (GLMM)
- Logistic Regression
- Poisson Regression
- Negative Binomial Regression
- Quasi-Poisson Regression
- Quasi-Binomial Regression
- Zero-Inflated Models (ZIP and ZINB)
- Hurdle Models
- Non-linear Models
- Generalized Additive Models (GAMs)
- Quantile Regression
- Multilevel Modeling

#### Multivariate Analysis
- Exploratory Factor Analysis
- Confirmatory Factor Analysis
- Latent Profile Analysis
- Path Analysis
- Structural Equation Modeling
- Multidimensional Scaling
- Cluster Analysis

#### Specialized Analysis Techniques
- Time Series Analysis
- Stationarity, Differencing, and Autocorrelation
- Seasonality and Cyclical Trends
- Autoregressive Models
- Moving Average Models
- ARIMA Models
- SARIMA Models (Seasonal ARIMA)
- Forecasting Techniques
- Vector Autoregression (VAR)
- State Space Models and the Kalman Filter
- Multivariate Time Series Analysis
- ARCH/GARCH Models

#### Longitudinal Data and Growth Models
- Basics of Longitudinal Data Analysis
- Panel Data Analysis
- Cross-Lagged Panel Models (CLPM)
- Intensive Longitudinal Methods
- Latent Growth Curve Modeling (LGCM)
- Survival Analysis
- Multilevel Models for Longitudinal Data
- Structural Equation Modeling for Longitudinal Data
- Missing Data in Longitudinal Studies

#### Causal Inference
- Experimental Design
- Quasi-experimental Design
- Natural Experiments
- Instrumental Variable Techniques
- Matching and Weighting for Causal Inference
- Propensity Score Analysis
- Difference in Differences
- Interrupted Time Series
- Directed Acyclic Graphs for Causal Inference
- Causal Mediation Analysis
- Sensitivity Analysis
- Counterfactual Frameworks
- Structural Causal Models
- G-Estimation of Structural Nested Models

#### Handling Special Data Conditions

- Managing Missing Data
    + Understanding the nature of missing data
    + Popular methods for handling missing data:
- Handling Outliers
    + Detecting outliers: visual methods (box plots, scatter plots), statistical methods (z-score, IQR method)
    + Techniques for managing outliers
- Strategies for Non-Normal Data
    + Understanding the concept of skewness and kurtosis
    + Applying transformations to deal with non-normal data
- Dealing with Imbalanced Data
    + Grasping the issues associated with imbalanced data
    + Implementing resampling methods: oversampling the minority class, undersampling the majority class
    + Applying advanced techniques: Synthetic Minority Over-sampling Technique (SMOTE), Adaptive Synthetic (ADASYN) sampling method
    + Utilizing cost-sensitive learning
    
- Advanced Data Techniques
    + Bootstrapping Methods
    + Cross-validation techniques
    + Ensemble methods


#### Scale Development and Psychometrics

- Classical Test Theory (CTT)
- Item Analysis
- Reliability Analysis
- Validity Analysis
- Scale Construction and Development
- Item Response Theory (IRT)

#### Meta-Analysis
- Understanding the concept of meta-analysis
- Fixed-Effect and Random-Effects Models
- Heterogeneity in meta-analysis
- Meta-Regression
- Meta-analytic Structural Equation Modeling (MASEM)
- Assessing Publication Bias
- Interpretation and Presentation of Results

#### Cross-Validation and Model Selection Techniques
- Understanding overfitting and the need for model validation
- Holdout validation, k-fold cross-validation, leave-one-out cross-validation
- Model Selection Techniques: Akaike Information Criterion (AIC), Bayesian Information Criterion (BIC), Adjusted R-square
- Regularization techniques: Ridge, Lasso, Elastic Net

#### Network Analysis
- Understanding the concept of network analysis
- Social Network Analysis
- Centrality Measures
- Community Detection
- Network Dynamics

#### Handling Large Data Sets (Big Data)
- Data Reduction Techniques
- Distributed Computing frameworks
- Data Cleaning and Transformation Techniques
- Machine Learning at Scale

#### Bayesian Statistics
- Understanding Bayesian principles and Bayes' Theorem
- Bayesian Inference
- Common Bayesian Models
- Bayesian Hierarchical Models
- Bayesian Networks
- Machine Learning in Bayesian Statistics